package twilio

const (
	ENV_TWILIO_SID             = "TWILIO_SID"
	ENV_TWILIO_TEST_SID        = "TWILIO_TEST_SID"
	ENV_TWILIO_AUTH_TOKEN      = "TWILIO_AUTH_TOKEN"
	ENV_TWILIO_TEST_AUTH_TOKEN = "TWILIO_TEST_AUTH_TOKEN"
	ENV_TWILIO_NUM_FROM        = "TWILIO_NUM_FROM"
	ENV_TWILIO_NUM_TO          = "TWILIO_NUM_TO"
)
